server:
  port: 9191
  
spring:  h2:    console:      enabled: true
  application:    name: PAYMENT-SERVICE
    
logging:  file: C:\Users\Rohit Dhingra\git\ApiGatewayEurekaHystrixRep\logs\microservice.log
   